# Tell wotan to use the valtyr module for linting.
modules: "@fimbul/valtyr"

# Valtýr configuration.
valtyr:

  # Use the Vé preprocessor for all *.vue files.
  # Valtýr will still run for *.ts files by default.
  overrides:
    - files: "*.vue"
      processor: "@fimbul/ve"